version: '3'

services:
  dind:
    image: docker:dind
    privileged: true
    expose:
      - 2375
    env_file:
    - ./.env
    environment:
    - DOCKER_TLS_CERTDIR=

  runner:
    build: .
    depends_on:
      - dind
    stop_grace_period: 60s
    restart: always
    privileged: true
    env_file:
      - ./.env
    links:
      - dind
    environment:
      DOCKER_HOST: tcp://dind:2375
