#!/bin/bash

DOCKER_USER=collinmcneese
DOCKER=docker
DIND_RUNNER_NAME="ghcr.io/collinmcneese/github_actions_runners-arc-container-dind"
OS_IMAGE=ubuntu-22.04
TARGETPLATFORM='arm64'

RUNNER_VERSION=2.315.0
RUNNER_CONTAINER_HOOKS_VERSION=0.6.0
DOCKER_VERSION=24.0.7

if [[ "${TARGETPLATFORM}" == 'arm64' ]]; then
  DOCKER_TAG="${DIND_RUNNER_NAME}:${RUNNER_VERSION}-arm64"
else
  DOCKER_TAG="${DIND_RUNNER_NAME}:${RUNNER_VERSION}"
fi


${DOCKER} build \
  --build-arg TARGETPLATFORM=${TARGETPLATFORM} \
  --build-arg RUNNER_VERSION=${RUNNER_VERSION} \
  --build-arg RUNNER_CONTAINER_HOOKS_VERSION=${RUNNER_CONTAINER_HOOKS_VERSION} \
  --build-arg DOCKER_VERSION=${DOCKER_VERSION} \
  -f Dockerfile \
  -t ${DOCKER_TAG} .
