name: Test Docker Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high

      - name: Output Collector
        id: output-collector
        uses: collinmcneese/file-output-collector@main
        with:
          file: "./VERSION"

      - name: Prep
        run: |
          echo Building with Runner version ${{ steps.output-collector.outputs.output }}
          echo ${{ steps.output-collector.outputs.output }} | grep 2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta-docker
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        id: build-docker
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ./docker
          push: false
          labels: ${{ steps.meta-docker.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            RUNNER_VERSION=${{ steps.output-collector.outputs.output }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.output-collector.outputs.output }}

      - name: debug build
        run: |
          echo "digest: ${{ steps.build-docker.outputs.digest }}"
          echo "metadata: ${{ steps.build-docker.outputs.metadata }}"
          echo "imageid: ${{ steps.build-docker.outputs.imageid }}"

      - name: docker - Build Attestation
        continue-on-error: true
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.output-collector.outputs.output }}"
          subject-digest: "${{ steps.build-docker.outputs.digest }}"
          push-to-registry: false

  build-actions-runner-image:
    env:
      IMAGE_NAME: collinmcneese/actions-runner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high

      - name: Output Collector
        id: output-collector
        uses: collinmcneese/file-output-collector@main
        with:
          file: "./VERSION"

      - name: Prep
        run: |
          echo Building with Runner version ${{ steps.output-collector.outputs.output }}
          echo ${{ steps.output-collector.outputs.output }} | grep 2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta-docker
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        id: build-docker
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ./actions-runner
          push: false
          labels: ${{ steps.meta-docker.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            RUNNER_VERSION=${{ steps.output-collector.outputs.output }}
            RUNNER_CONTAINER_HOOKS_VERSION=0.6.1
            DOCKER_VERSION=27.1.1
            BUILDX_VERSION=0.16.2
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.output-collector.outputs.output }}

      - name: debug build
        run: |
          echo "digest: ${{ steps.build-docker.outputs.digest }}"
          echo "metadata: ${{ steps.build-docker.outputs.metadata }}"
          echo "imageid: ${{ steps.build-docker.outputs.imageid }}"

      - name: docker - Build Attestation
        continue-on-error: true
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.output-collector.outputs.output }}"
          subject-digest: "${{ steps.build-docker.outputs.digest }}"
          push-to-registry: false

  build-runner-no-dind-image:
    env:
      IMAGE_NAME: collinmcneese/runner-no-dind
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high

      - name: Output Collector
        id: output-collector
        uses: collinmcneese/file-output-collector@main
        with:
          file: "./VERSION"

      - name: Prep
        run: |
          echo Building with Runner version ${{ steps.output-collector.outputs.output }}
          echo ${{ steps.output-collector.outputs.output }} | grep 2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta-docker
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        id: build-docker
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ./runner-no-dind
          push: false
          labels: ${{ steps.meta-docker.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            RUNNER_VERSION=${{ steps.output-collector.outputs.output }}
            RUNNER_CONTAINER_HOOKS_VERSION=0.6.1
            DOCKER_VERSION=27.1.1
            BUILDX_VERSION=0.16.2
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.output-collector.outputs.output }}

      - name: debug build
        run: |
          echo "digest: ${{ steps.build-docker.outputs.digest }}"
          echo "metadata: ${{ steps.build-docker.outputs.metadata }}"
          echo "imageid: ${{ steps.build-docker.outputs.imageid }}"

      - name: docker - Build Attestation
        continue-on-error: true
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.output-collector.outputs.output }}"
          subject-digest: "${{ steps.build-docker.outputs.digest }}"
          push-to-registry: false
