name: Test Docker Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Output Collector
        id: output-collector
        uses: collinmcneese/file-output-collector@main
        with:
          file: "./VERSION"

      - name: Prep
        run: |
          echo Building with Runner version ${{ steps.output-collector.outputs.output }}
          echo ${{ steps.output-collector.outputs.output }} | grep 2

      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
        with:
          context: ./docker
          push: false
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            RUNNER_VERSION=${{ steps.output-collector.outputs.output }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.output-collector.outputs.output }}
